### ISSUE TITLE
'chmod' Error

### ISSUE THREAD

**Issue by maxicandelero** [kevinpainchaud/simple-ftp-deploy-action#4]
Hi,
First, thanks for this great action.

I try to use it but i have received an error. My ftp site is over a Windows Server, i can read that these maybe there are the problem.
This is the error, over a basic configuration.

![image](https://user-images.githubusercontent.com/19535277/91596118-14d3f980-e93b-11ea-9ad2-9d0d65bc0ac4.png)

![image](https://user-images.githubusercontent.com/19535277/91596414-3339f500-e93b-11ea-9a3d-8e58f17622d6.png)

Am I missing something?
Thanks.

**Comment by hubert17** [comment]
I have the same issue. I wish for an "ignore" option for this error so that workflow can freely go successful.

**Comment by kevinpainchaud** [comment]
Hello,

Thank you for your participation and sorry for the response time.

I added this new option : `no_perms`. I think your problem is related to this (according to https://stackoverflow.com/a/9639626).
Can you test on this feature branch ? https://github.com/kevinpainchaud/simple-ftp-deploy-action/tree/feature-no-perms
In your `main.yml`, you can refer to it like this : 

- `uses: kevinpainchaud/simple-ftp-deploy-action@feature-no-perms`

And adding this new option : 

- `no_perms: "true"`

If it's works for you, i'm gonna release this into a new version. 😊

Thx.

**Comment by maxicandelero** [comment]
Hi Kevin,

I have did some tests  and it works well. 

Thanks!!!

**Comment by kevinpainchaud** [comment]
Great!
Happy to hear that was related to this option.

However, some modifications have be done since my last answer.
Now, you should rather use this option in your workflow file:

- `other_flags: "--no-perms"`

This option allows to insert a raw string of flags for lftp for more flexibility.

And use the latest version (freshly released):

- `uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.0`

Thx again for your contribution.
Bye.

**Comment by maxicandelero** [comment]
Hi Kevin,

I used the latest version, but it didn't work. I received this error...

![image](https://user-images.githubusercontent.com/19535277/94160384-f1796d00-fe5a-11ea-9cc0-1e5ff8eb6ab8.png)

The file was transferred, but the workflow was stopped. Then, I tested again the branch "feature-no-perms", and it was good.

Thx again. Have a good day!

**Comment by kevinpainchaud** [comment]
Could you please paste your workflow file content here so I can investigate?

**Comment by maxicandelero** [comment]
Yes, this doesn't work...

![image](https://user-images.githubusercontent.com/19535277/94189121-b7bb5d00-fe80-11ea-9eb5-bd5a17770342.png)

This works...

![image](https://user-images.githubusercontent.com/19535277/94189566-4a5bfc00-fe81-11ea-9b41-0d60d69f6b83.png)

**Comment by kevinpainchaud** [comment]
The problem is solved (thanks to @alesmenzel)!
You just have to use the latest release: https://github.com/kevinpainchaud/simple-ftp-deploy-action/releases/tag/v1.2.1
Bye. 👋

**Comment by maxicandelero** [comment]
Yes Kevin, it worked well. 
Thanks to both. Bye!
